name: davidkhala.data
on: push
jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.11', latest]
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          tests: format/tests
          test-entry-point: pytest
          working-directory: format
          version: ${{matrix.version}}
  frame:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '3.10', latest ]
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          tests: frame/tests
          test-entry-point: pytest
          working-directory: frame
          version: ${{matrix.version}}
  dash:
    runs-on: ubuntu-latest
    env:
      container: dash
    steps:
      - uses: actions/checkout@main
      - run: export DOCKER_BUILDKIT=1
      - run: docker build -t dash:latest visualization/app/dash
      - run: docker run --name $container -d dash:latest
      - run: curl https://raw.githubusercontent.com/davidkhala/containers/refs/heads/main/cli/health.sh | bash -s wait-until-healthy $container
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '3.11', latest ]
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          tests: integration/tests
          test-entry-point: pytest
          working-directory: integration
          version: ${{matrix.version}}
        env:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}